// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALVStIUKmRPM1yi0fkVek6ro70h3VexAA',
    appId: '1:289602236276:web:41a5b40bdc760713c4c621',
    messagingSenderId: '289602236276',
    projectId: 'remindeme-d926a',
    authDomain: 'remindeme-d926a.firebaseapp.com',
    storageBucket: 'remindeme-d926a.appspot.com',
    measurementId: 'G-CG8ZE7Y02X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2_01aondz8i4K9U6E68ebroizExBMJg',
    appId: '1:289602236276:android:a1b9f3dbba4bdb39c4c621',
    messagingSenderId: '289602236276',
    projectId: 'remindeme-d926a',
    storageBucket: 'remindeme-d926a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNuFrJkfM49YkDi8ayz9gO9Mdq_WF28U',
    appId: '1:289602236276:ios:3fd111e55d56aa69c4c621',
    messagingSenderId: '289602236276',
    projectId: 'remindeme-d926a',
    storageBucket: 'remindeme-d926a.appspot.com',
    iosBundleId: 'com.example.questraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNuFrJkfM49YkDi8ayz9gO9Mdq_WF28U',
    appId: '1:289602236276:ios:3fd111e55d56aa69c4c621',
    messagingSenderId: '289602236276',
    projectId: 'remindeme-d926a',
    storageBucket: 'remindeme-d926a.appspot.com',
    iosBundleId: 'com.example.questraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMkM_mMG89_Hhia7C1XYQXMMXJzrBQ7Oo',
    appId: '1:289602236276:web:f2265b16d8e0bca8c4c621',
    messagingSenderId: '289602236276',
    projectId: 'remindeme-d926a',
    authDomain: 'remindeme-d926a.firebaseapp.com',
    storageBucket: 'remindeme-d926a.appspot.com',
    measurementId: 'G-1TPGJH9572',
  );
}
